version: "3.7"

services:
  # web
  web:
    image: nginx:alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./www:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # php
  php:
    build: .
    restart: always
    volumes:
      - ./www:/code

  # mysql
  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    depends_on:
      - db

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9999:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example

volumes:
  db_data: {}
